apiVersion: v1
kind: Service
metadata:
  name: infnet-guia-service
spec:
  type: NodePort
  selector:
    app: infnet-guia
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 3000
